"""initial

Revision ID: 0001
Revises: 0001
Create Date: 2023-03-14 20:09:23.900859

"""
# revision identifiers, used by Alembic.
revision = "0001"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
